import type { Metadata } from "next";
import { Junge } from "next/font/google"; 
import "./globals.css";

const junge = Junge({
  weight: "400",         
  subsets: ["latin"],
  variable: "--font-junge"
})
export const metadata: Metadata = {
  title: "E Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${junge.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
