import type { Metadata } from "next";
import { Junge, Julius_Sans_One, Overpass } from "next/font/google"; 
import "./globals.css";

const junge = Junge({
  weight: "400",         
  subsets: ["latin"],
  variable: "--font-junge"
})

const julius = Julius_Sans_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-julius"
})

const overpass = Overpass({
  weight: "300",
  subsets: ["latin"],
  variable: "--font-overpass"
})
export const metadata: Metadata = {
  title: "E Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`data-scroll-behavior="smooth" ${overpass.variable} ${julius.variable} ${junge.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
